name: multi arch build

on:
  push:
    branches: master
  # rebuild every week to pick up any updates
  #schedule:
  #   - cron: '0 10 1 * *' # 1st of month at 10am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build \
          --tag nexusuw/mell-gibson-mustache:latest --tag nexusuw/mell-gibson-mustache:$(date -u +'%Y%m%d') --push  \
          --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 .
